version: '3.9'

services:
  sernsorrestservice:
    image: postgres:14.5
    environment:
      POSTGRES_USER: '12345'
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: 'sensor_app_db'
    ports:
      - '5432:5432'
